name: Docker Image CI

on:
  push:
    branches: ["stage"]

env:
  REGISTRY: geraldbar
  IMAGE_NAME: kubelabs_publicapi2
  OPS_BRANCH: main
  OPS_REPO: GeraldBarquero/ops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        with:
          fetch-depth: 0
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_ENV= ${{ secrets.APP_ENV }}
        
      - name: Run test
        run: docker run --rm --name api p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest  

      
