name: hello-world

on:
  push:
    branch: ["stage"]

env:
  TEXT: "Gerald Barquero Valverde"

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print-to-screen
        run: echo "Hello World ${{ env.TEXT }}! - ${{ secrets.SECRET_NAME }}"